const express = require('express')
const app = express()
const dotenv = require('dotenv').config()
const mongoose = require('mongoose')
const bodyParser = require('body-parser')
const connectdb = require('./db/database')
const student = require('./routers/student')
const examiner = require('./routers/examiner')
const admin = require('./routers/admin')
const auth = require('./routers/auth')
const cors = require('cors')

app.use(cors())
app.use(bodyParser.json())
app.use(express.json())

app.use('/api/student', student)
app.use('/api/examiner', examiner)
app.use('/api/admin', admin)
app.use('/api/auth', auth)
app.listen(process.env.port, () => {
  console.log(`${process.env.port} is connected`)
  connectdb()
})
